site_name: Evflow Documentation
site_description: Design and API documentation for the Evflow project.
site_author: Evflow Project
repo_url: https://github.com/evflow/docs

docs_dir: 'docs'
pages:
- ['index.md', 'Home']
- ['introduction/what-even-is.md', 'Introduction', 'What is Evflow?']
- ['introduction/why.md', 'Introduction', 'Why?']
- ['introduction/project-goals.md', 'Introduction', 'Project Goals']
- ['concepts/event-loop.md', 'Concepts', 'The Event Loop']
- ['concepts/event-devices.md', 'Concepts', 'Event Devices']
- ['usage/logging.md', 'Usage', 'Logging']

theme: readthedocs
site_favicon: favicon.ico
